apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: le-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: noreply@my-domain.com
    privateKeySecretRef:
      name: le-staging
    dns01:
      providers:
        - name: my-gcp-project
          clouddns:
            serviceAccountSecretRef:
              name: gcloud
              key: key.json
            project: my-gcp-project
