---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: web
  namespace: wordpress
spec:
  acme:
    config:
    - dns01:
        provider: my-gcp-project
      domains:
      - my-domain.com
  commonName: my-domain.com
  dnsNames:
  - my-domain.com
  issuerRef:
    kind: ClusterIssuer
    name: le-production
  secretName: my-website-tls
